In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('rideshare_kaggle.csv')

In [6]:
df['cab_type'].value_counts(normalize=True)

Uber    0.556455
Lyft    0.443545
Name: cab_type, dtype: float64

In [7]:
uber_df=df.loc[(df['cab_type']=='Uber'),:].reset_index(drop=True)

In [8]:
lyft_df=df.loc[(df['cab_type']=='Lyft'),:].reset_index(drop=True)

In [9]:
## Let's start with Uber

In [10]:
lyft_df[lyft_df.duplicated(subset='id',keep=False)]
uber_df[uber_df.duplicated(subset='id',keep=False)]

## No duplicate booking ids

Empty DataFrame
Columns: [id, timestamp, hour, day, month, datetime, timezone, source, destination, cab_type, product_id, name, price, distance, surge_multiplier, latitude, longitude, temperature, apparentTemperature, short_summary, long_summary, precipIntensity, precipProbability, humidity, windSpeed, windGust, windGustTime, visibility, temperatureHigh, temperatureHighTime, temperatureLow, temperatureLowTime, apparentTemperatureHigh, apparentTemperatureHighTime, apparentTemperatureLow, apparentTemperatureLowTime, icon, dewPoint, pressure, windBearing, cloudCover, uvIndex, visibility.1, ozone, sunriseTime, sunsetTime, moonPhase, precipIntensityMax, uvIndexTime, temperatureMin, temperatureMinTime, temperatureMax, temperatureMaxTime, apparentTemperatureMin, apparentTemperatureMinTime, apparentTemperatureMax, apparentTemperatureMaxTime]
Index: []

[0 rows x 57 columns]

In [11]:
##### pd.to_datetime(uber_df['timestamp'], unit='s', utc=True).dt.tz_convert('America/New_York') will give time wrt to gmt time
uber_df['booking_time']=pd.to_datetime(uber_df['timestamp'], unit='s', utc=True)
uber_df['booking_date']=uber_df['booking_time'].apply(lambda x: x.date())
uber_df['booking_day']=uber_df['booking_date'].apply(lambda x: x.day)
uber_df['booking_month']=uber_df['booking_date'].apply(lambda x: x.month)
uber_df['booking_year']=uber_df['booking_date'].apply(lambda x: x.year)
uber_df['booking_hour']=uber_df['booking_time'].apply(lambda x: x.time)
uber_df['booking_weekday']=uber_df['booking_time'].dt.dayofweek
uber_df['booking_day_weekend']=uber_df['booking_time'].apply(lambda x: x.dayofweek // 5 == 1)
uber_df['booking_day_weekend']=uber_df['booking_day_weekend'].astype(int)
uber_df['booking_minute']=uber_df['booking_time'].apply(lambda x: x.minute)

In [12]:
uber_df['booking_time'][0]-uber_df['booking_time'][1]
divmod(uber_df['booking_time'][0]-uber_df['booking_time'][1], 3600)[0].seconds

86099

In [13]:
uber_df.drop(['hour','day','month','datetime','timestamp'],axis=1,inplace=True)

In [14]:
for i in ['windGustTime','temperatureHighTime','temperatureLowTime','sunriseTime','sunsetTime','uvIndexTime','temperatureMinTime','temperatureMaxTime']:
    uber_df["{}_hour".format(i)]=pd.to_datetime(uber_df[i], unit='s', utc=True)
#     uber_df["{}_hour".format(i)]=uber_df[i].apply(lambda x: x.time)
#     uber_df[i]=uber_df[i].apply(lambda x: x.time)

In [15]:
uber_df.drop(['apparentTemperatureHigh', 'apparentTemperatureHighTime',
       'apparentTemperatureLow', 'apparentTemperatureLowTime','apparentTemperatureMin', 'apparentTemperatureMinTime',
       'apparentTemperatureMax', 'apparentTemperatureMaxTime'],axis=1,inplace=True)

In [16]:
uber_df.drop(['windGustTime','temperatureHighTime','temperatureLowTime','sunriseTime','sunsetTime','uvIndexTime','temperatureMinTime','temperatureMaxTime'],axis=1,inplace=True)

In [17]:
uber_df.drop(['temperatureHigh',
       'temperatureLow'],axis=1,inplace=True)

In [18]:
uber_df['source'].unique()

array(['North End', 'Beacon Hill', 'North Station', 'Boston University',
       'South Station', 'Fenway', 'Theatre District', 'West End',
       'Back Bay', 'Northeastern University', 'Haymarket Square',
       'Financial District'], dtype=object)

In [19]:
# Adding diurnal air temperature variation.
uber_df['temp_var'] = uber_df['temperatureMax'] - uber_df['temperatureMin']

def distance_category(x):
    if x<=2:
        return '[0,2]'
    elif x<=4:
        return '(2-4]'
    elif x<=6:
        return '(4-6]'
    else:
        return '(6-8]'

uber_df['dist_cat']=uber_df['distance'].apply(distance_category)

In [20]:
days = [2, 7, 14,30]
weather_features=['temperature','precipIntensity','humidity','ozone']
for day in days:
    for feature in weather_features:
        uber_df[f'{feature}_{day}_day_mov_avg'] = uber_df.groupby(['source','destination','booking_month'])[feature].transform(lambda x: x.shift(1).rolling(window=day,min_periods=0,center=False).mean())

In [214]:
for i in ['temperature_2_day_mov_avg',
       'precipIntensity_2_day_mov_avg', 'humidity_2_day_mov_avg',
       'ozone_2_day_mov_avg', 'temperature_7_day_mov_avg',
       'precipIntensity_7_day_mov_avg', 'humidity_7_day_mov_avg',
       'ozone_7_day_mov_avg', 'temperature_14_day_mov_avg',
       'precipIntensity_14_day_mov_avg', 'humidity_14_day_mov_avg',
       'ozone_14_day_mov_avg', 'temperature_30_day_mov_avg',
       'precipIntensity_30_day_mov_avg', 'humidity_30_day_mov_avg',
       'ozone_30_day_mov_avg']:
    uber_df[i]=uber_df.groupby(['source','destination'])[i].transform(lambda x: x.fillna(x.mean()))

In [22]:
# Adding differences from the moving averages to identify sudden dips and hikes.
uber_df['precipIntensity_diff_2'] = uber_df['precipIntensity'] - uber_df['precipIntensity_2_day_mov_avg']
uber_df['precipIntensity_diff_7'] = uber_df['precipIntensity'] - uber_df['precipIntensity_7_day_mov_avg']
uber_df['precipIntensity_diff_14'] = uber_df['precipIntensity'] - uber_df['precipIntensity_14_day_mov_avg']
uber_df['precipIntensity_diff_30'] = uber_df['precipIntensity'] - uber_df['precipIntensity_30_day_mov_avg']


uber_df['temperature_diff_2'] = uber_df['temperature'] - uber_df['temperature_2_day_mov_avg']
uber_df['temperature_diff_7'] = uber_df['temperature'] - uber_df['temperature_7_day_mov_avg']
uber_df['temperature_diff_14'] = uber_df['temperature'] - uber_df['temperature_14_day_mov_avg']
uber_df['temperature_diff_30'] = uber_df['temperature'] - uber_df['temperature_30_day_mov_avg']


uber_df['humidity_diff_2'] = uber_df['humidity'] - uber_df['humidity_2_day_mov_avg']
uber_df['humidity_diff_7'] = uber_df['humidity'] - uber_df['humidity_7_day_mov_avg']
uber_df['humidity_diff_14'] = uber_df['humidity'] - uber_df['humidity_14_day_mov_avg']
uber_df['humidity_diff_30'] = uber_df['humidity'] - uber_df['humidity_30_day_mov_avg']


uber_df['ozone_diff_2'] = uber_df['ozone'] - uber_df['ozone_2_day_mov_avg']
uber_df['ozone_diff_7'] = uber_df['ozone'] - uber_df['ozone_7_day_mov_avg']
uber_df['ozone_diff_14'] = uber_df['ozone'] - uber_df['ozone_14_day_mov_avg']
uber_df['ozone_diff_30'] = uber_df['ozone'] - uber_df['ozone_30_day_mov_avg']

In [23]:
# divmod(uber_df['booking_time'][0]-uber_df['booking_time'][1], 3600)[0].seconds

uber_df['bktime_tmpmaxtime_diff']=uber_df.apply(lambda x: (divmod((x['booking_time']-x['temperatureHighTime_hour']).total_seconds(),60)[0])/60,axis=1)
uber_df['bktime_tmpmaxtime_diff']=uber_df['bktime_tmpmaxtime_diff'].astype(int)

In [24]:
uber_df['bktime_sunrisetime_diff']=uber_df.apply(lambda x: (divmod((x['booking_time']-x['sunriseTime_hour']).total_seconds(),60)[0])/60,axis=1)
uber_df['bktime_sunrisetime_diff']=uber_df['bktime_sunrisetime_diff'].astype(int)

In [25]:
uber_df['bktime_sunsettime_diff']=uber_df.apply(lambda x: (divmod((x['booking_time']-x['sunsetTime_hour']).total_seconds(),60)[0])/60,axis=1)
uber_df['bktime_sunsettime_diff']=uber_df['bktime_sunsettime_diff'].astype(int)

In [27]:
import googlemaps
gmaps = googlemaps.Client(key='AIzaSyDXw0dws63kO49Uf8H3R38hQvnPzrfg9FM')

In [45]:
regions=list(uber_df.groupby(['source','latitude','longitude']).groups.keys())

In [51]:
### Obtaining the number of restaurants
import time

restaurants = []
def restaurant_response(response_items, tag):
    restaurant_responses = []
    for item in response_items:
        item_dict = {}
        item_dict['tag'], item_dict['name'], item_dict['place_id'], item_dict['price_level'], item_dict['rating'], item_dict['user_ratings_total'] = tag, item.get('name'), item.get('place_id'), item.get('price_level'), item.get('rating'), item.get('user_ratings_total')
        restaurant_responses.append(item_dict)
    return restaurant_responses


for i,barrio in enumerate(regions):
    query_barrio = barrio[0] + " Boston"
    lat = barrio[1]
    lng = barrio[2]
    flag = False
    counter = 0
    while flag == False:
        if counter == 0:
            results = gmaps.places(type="restaurant", location=[lat, lng], radius=2000)
            response_items = results['results']
            restaurants.extend(restaurant_response(response_items, barrio))
            counter += 1
        else:
            if results.get('next_page_token') is None:
                flag = True
            else:
                next_page = results.get('next_page_token')
                time.sleep(2)
                results = gmaps.places(type="restaurant", location=[lat, lng], radius=2000, page_token=next_page)
                response_items = results['results']
                restaurants.extend(restaurant_response(response_items, barrio))
                counter += 1

In [31]:
# cuisines = ['traditional', 'mexican', 'latin', 'burger', 'pizza', 'high cuisine', 'american', 'italian', 'turkish', 'mediterranean', 'chinese', 'asian', 'indian', 'japanese']
# place = gmaps.geocode("Valencia")
# place_info = place[0]
# geo_results = place_info['geometry']
# geo_coordinates = geo_results['location']
# lat = geo_coordinates['lat']
# lng = geo_coordinates['lng']
# for cuisine in cuisines:
#     print(len(restaurants))
#     flag = False
#     counter = 0
#     while flag == False:
#         if counter == 0:
#             results = gmaps.places(query=(cuisine, "restaurants in Valencia"), type="restaurant", location=[lat, lng])
#             response_items = results['results']
#             restaurants.extend(restaurant_response(response_items, cuisine))
#             counter += 1
#         else:
#             if results.get('next_page_token') is None:
#                 flag = True
#             else:
#                 next_page = results.get('next_page_token')
#                 time.sleep(2)
#                 results = gmaps.places(query=(cuisine, "restaurants in Valencia"), type="restaurant", location=[lat, lng], page_token=next_page)
#                 response_items = results['results']
#                 restaurants.extend(restaurant_response(response_items, cuisine))
#                 counter += 1

[{'tag': 'North End',
  'name': 'Nan Xiang Express - Boston Chinatown',
  'place_id': 'ChIJY_SBUzx744kR0vjhWa46VC0',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 281},
 {'tag': 'North End',
  'name': 'Great Chef Chinese Food at Day Square',
  'place_id': 'ChIJqZCnlklw44kRBYOxlFw_PUU',
  'price_level': 1,
  'rating': 4,
  'user_ratings_total': 521},
 {'tag': 'North End',
  'name': "El Jefe's Taqueria - Boston Common",
  'place_id': 'ChIJP_FWr4l744kRvWI1JTsVqQg',
  'price_level': 1,
  'rating': 4.8,
  'user_ratings_total': 1952},
 {'tag': 'North End',
  'name': 'La Hacienda East Boston',
  'place_id': 'ChIJqRX4QFtw44kREhDeTRz1ECU',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 2333},
 {'tag': 'North End',
  'name': 'Taquería Jalisco',
  'place_id': 'ChIJw-UwpUlw44kRCGEtowbEJ08',
  'price_level': 1,
  'rating': 4.7,
  'user_ratings_total': 1321},
 {'tag': 'North End',
  'name': 'Los Alebrijes Mexican Restaurant',
  'place_id': 'ChIJO9faZwBx44kRMYhLRqLKRog',
  'price_level': None,
  'rating': 4.8,
  'user_ratings_total': 113},
 {'tag': 'North End',
  'name': "Giacomo's Boston North End",
  'place_id': 'ChIJKRXowbtz44kRORvv6Mx_MDw',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 2847},
 {'tag': 'North End',
  'name': 'South Street Diner',
  'place_id': 'ChIJ0d-eHXl644kR-9gAty9Z068',
  'price_level': 1,
  'rating': 4.1,
  'user_ratings_total': 3720},
 {'tag': 'North End',
  'name': 'Boston Kitchen Pizza',
  'place_id': 'ChIJ7V9fn3d644kRzotUsPPwfik',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 837},
 {'tag': 'North End',
  'name': 'Flavor Boom! Milk Street',
  'place_id': 'ChIJv4g4RB9x44kRCrHWjovnE2U',
  'price_level': 1,
  'rating': 4.8,
  'user_ratings_total': 302},
 {'tag': 'North End',
  'name': 'Jumbo Seafood',
  'place_id': 'ChIJrYKsR3h644kRhdRKR6aC7lk',
  'price_level': 2,
  'rating': 3.9,
  'user_ratings_total': 812},
 {'tag': 'North End',
  'name': 'El Palmar Restaurant',
  'place_id': 'ChIJF5JVoUlw44kRm5ovoSanUMA',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 64},
 {'tag': 'North End',
  'name': 'Bon Me - Boston Public Market',
  'place_id': 'ChIJt6NEXI9w44kRrH_axqtlJcw',
  'price_level': 1,
  'rating': 3.8,
  'user_ratings_total': 80},
 {'tag': 'North End',
  'name': 'Topacio',
  'place_id': 'ChIJuZEnQ1tw44kRIKcfHuUE-w8',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 381},
 {'tag': 'North End',
  'name': 'Row 34',
  'place_id': 'ChIJ95EjMYB644kRHrS_JLt0-Lg',
  'price_level': 3,
  'rating': 4.6,
  'user_ratings_total': 3536},
 {'tag': 'North End',
  'name': 'Mi Pueblito Restaurant',
  'place_id': 'ChIJn3q0Q1Bw44kRp-M-kvgdJNk',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 1079},
 {'tag': 'North End',
  'name': 'Kelley Square Pub',
  'place_id': 'ChIJkXA8bkVw44kRDg_40pnFqXU',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 965},
 {'tag': 'North End',
  'name': 'Umami Sushi',
  'place_id': 'ChIJe645PYNw44kRkkaFYkNpblk',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 79},
 {'tag': 'North End',
  'name': 'Libertine North End',
  'place_id': 'ChIJ4VwScehx44kREVopKPp1aH0',
  'price_level': None,
  'rating': 4.2,
  'user_ratings_total': 311},
 {'tag': 'North End',
  'name': 'Cactus Mexican Grill',
  'place_id': 'ChIJ804XJF1w44kRR7oJQMlArZs',
  'price_level': 1,
  'rating': 4.3,
  'user_ratings_total': 626},
 {'tag': 'North End',
  'name': 'Tu Metapan',
  'place_id': 'ChIJx0kxu0lw44kRN5N1HA6M4lg',
  'price_level': 1,
  'rating': 4.2,
  'user_ratings_total': 204},
 {'tag': 'North End',
  'name': 'Chinese Dragon',
  'place_id': 'ChIJqVgIo1pw44kR5jziu8skJzw',
  'price_level': 1,
  'rating': 3.4,
  'user_ratings_total': 391},
 {'tag': 'North End',
  'name': 'Waverly Kitchen & Bar Charlestown',
  'place_id': 'ChIJZxEaTnFx44kRq3wYQXk-beo',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 320},
 {'tag': 'North End',
  'name': 'Pazza on Porter',
  'place_id': 'ChIJAzMVIrBx44kRn1hO8LO3fIY',
  'price_level': 2,
  'rating': 4.8,
  'user_ratings_total': 1152},
 {'tag': 'North End',
  'name': 'Restaurante Montecristo',
  'place_id': 'ChIJ1Q6IFltw44kRQEjxW7VzMic',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 516},
 {'tag': 'North End',
  'name': 'Moxies Boston Seaport Restaurant',
  'place_id': 'ChIJ28zCvCh744kRDiXNE2oj8fE',
  'price_level': None,
  'rating': 4.6,
  'user_ratings_total': 656},
 {'tag': 'North End',
  'name': 'CABANA GRILL MEXICAN RESTAURANT',
  'place_id': 'ChIJdSaiBklw44kRb1gKEHVIUKA',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 344},
 {'tag': 'North End',
  'name': 'Boston Chowda Co',
  'place_id': 'ChIJb7nX2YVw44kRWSszA1fiSY8',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 1239},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJa6jJFwx644kRCqw6ohQtC6c',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 684},
 {'tag': 'North End',
  'name': 'New York Shawarma Guys',
  'place_id': 'ChIJvxepkFJx44kR4-Zh0PP4l9I',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 276},
 {'tag': 'North End',
  'name': 'Shake Shack Downtown Crossing',
  'place_id': 'ChIJqfY6M1hx44kRhMpDOx20h58',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 1226},
 {'tag': 'North End',
  'name': 'Shōjō Boston',
  'place_id': 'ChIJRV40Onh644kRFHLE15lzefw',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 1281},
 {'tag': 'North End',
  'name': 'Falafel King - Summer Street',
  'place_id': 'ChIJzTfDV4Jw44kRreMeXT6h7M0',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 367},
 {'tag': 'North End',
  'name': 'Etnias Bar & Grill',
  'place_id': 'ChIJa-VKR_xx44kRWcgiC3k6MY8',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 77},
 {'tag': 'North End',
  'name': 'Boston Sail Loft',
  'place_id': 'ChIJKz7ENohw44kR-Aq6LJoK9Sg',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 4959},
 {'tag': 'North End',
  'name': 'LoLa 42',
  'place_id': 'ChIJ5fhUn35w44kRASBYiai3-Oo',
  'price_level': 3,
  'rating': 4.1,
  'user_ratings_total': 481},
 {'tag': 'North End',
  'name': 'La Reina Cafeteria',
  'place_id': 'ChIJE3XCa0Vw44kRZG4zEo1_v1M',
  'price_level': 1,
  'rating': 4.6,
  'user_ratings_total': 185},
 {'tag': 'North End',
  'name': "Rabia's Dolce Fumo",
  'place_id': 'ChIJ9WWwLI9w44kRsRwCZgaSYuE',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 747},
 {'tag': 'North End',
  'name': 'DIG',
  'place_id': 'ChIJuX7FWrhx44kRMPL3BFnTwN8',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 452},
 {'tag': 'North End',
  'name': 'Punto Rojo',
  'place_id': 'ChIJQWKL1Fpw44kREh_osyGnWrk',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 331},
 {'tag': 'North End',
  'name': 'Rincon Limeño',
  'place_id': 'ChIJUbPD8Elw44kR8KL_ejmDDEI',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 1515},
 {'tag': 'North End',
  'name': "La Famiglia Giorgio's Restaurant",
  'place_id': 'ChIJv7k_M4lw44kRuVhaTg8i9UQ',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 2860},
 {'tag': 'North End',
  'name': 'Bootleg Special',
  'place_id': 'ChIJVVUV0nN644kR1h4t-eJfIqw',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 1232},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJPV8P0oVw44kRrsrB-5wblfc',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 195},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJNwzr4n5w44kRTQLYt6f6NTA',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 162},
 {'tag': 'North End',
  'name': 'The Daily Catch North End',
  'place_id': 'ChIJh5s-F4lw44kRVNNe4L7moqU',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 1611},
 {'tag': 'North End',
  'name': 'Cunard Tavern',
  'place_id': 'ChIJ91_I72dw44kR-qG_E1wMRcI',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 630},
 {'tag': 'North End',
  'name': 'Los Pinos Mexican Grill Restaurant',
  'place_id': 'ChIJs3A0bEVw44kRhYmT0M0Fris',
  'price_level': 2,
  'rating': 3.9,
  'user_ratings_total': 204},
 {'tag': 'North End',
  'name': "D'Parma Restaurant",
  'place_id': 'ChIJ66QUdF1w44kR6U9nceFRerY',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 550},
 {'tag': 'North End',
  'name': 'Seoul Restaurant',
  'place_id': 'ChIJ1fC9V5pw44kRM543U1ikebc',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 838},
 {'tag': 'North End',
  'name': 'French Quarter',
  'place_id': 'ChIJ772OyoFx44kR4shRgUGWaBQ',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 697},
 {'tag': 'North End',
  'name': 'Gaga Seafood Restaurant',
  'place_id': 'ChIJS4r5MXh644kRLFxWK1g5h_U',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 420},
 {'tag': 'North End',
  'name': 'Bono Restaurant and Catering',
  'place_id': 'ChIJt20blnFx44kRKh39FoxVqvs',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 143},
 {'tag': 'North End',
  'name': 'China Pearl Restaurant',
  'place_id': 'ChIJz5PKO3h644kR_zF5SEKH1Q0',
  'price_level': 2,
  'rating': 4,
  'user_ratings_total': 771},
 {'tag': 'North End',
  'name': 'Primo Pizza Restaurant',
  'place_id': 'ChIJMaYfl5tw44kRm0aMh_9Mz20',
  'price_level': 2,
  'rating': 4,
  'user_ratings_total': 102},
 {'tag': 'North End',
  'name': 'La Abundancia Bakery & Restaurant',
  'place_id': 'ChIJqTwuuVxw44kRjmO63x9ptH4',
  'price_level': 1,
  'rating': 4.3,
  'user_ratings_total': 147},
 {'tag': 'North End',
  'name': 'Union Oyster House',
  'place_id': 'ChIJMVYI84Vw44kRKNGrFHLCsVc',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 9752},
 {'tag': 'North End',
  'name': 'ReelHouse',
  'place_id': 'ChIJMfUm1l1w44kRxwjqOp81giY',
  'price_level': 3,
  'rating': 4.2,
  'user_ratings_total': 1258},
 {'tag': 'North End',
  'name': 'GRECO',
  'place_id': 'ChIJnz5X7w5644kR5mYdtXjIX6o',
  'price_level': 1,
  'rating': 4.6,
  'user_ratings_total': 1491},
 {'tag': 'North End',
  'name': 'La Chiva Restaurant',
  'place_id': 'ChIJtViR_Uhw44kRqRozf-0MLR0',
  'price_level': 1,
  'rating': 4.2,
  'user_ratings_total': 1131},
 {'tag': 'North End',
  'name': 'Nan Xiang Express - Boston Chinatown',
  'place_id': 'ChIJY_SBUzx744kR0vjhWa46VC0',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 281},
 {'tag': 'North End',
  'name': 'Great Chef Chinese Food at Day Square',
  'place_id': 'ChIJqZCnlklw44kRBYOxlFw_PUU',
  'price_level': 1,
  'rating': 4,
  'user_ratings_total': 521},
 {'tag': 'North End',
  'name': "El Jefe's Taqueria - Boston Common",
  'place_id': 'ChIJP_FWr4l744kRvWI1JTsVqQg',
  'price_level': 1,
  'rating': 4.8,
  'user_ratings_total': 1952},
 {'tag': 'North End',
  'name': 'La Hacienda East Boston',
  'place_id': 'ChIJqRX4QFtw44kREhDeTRz1ECU',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 2333},
 {'tag': 'North End',
  'name': 'Taquería Jalisco',
  'place_id': 'ChIJw-UwpUlw44kRCGEtowbEJ08',
  'price_level': 1,
  'rating': 4.7,
  'user_ratings_total': 1321},
 {'tag': 'North End',
  'name': 'Los Alebrijes Mexican Restaurant',
  'place_id': 'ChIJO9faZwBx44kRMYhLRqLKRog',
  'price_level': None,
  'rating': 4.8,
  'user_ratings_total': 113},
 {'tag': 'North End',
  'name': "Giacomo's Boston North End",
  'place_id': 'ChIJKRXowbtz44kRORvv6Mx_MDw',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 2847},
 {'tag': 'North End',
  'name': 'South Street Diner',
  'place_id': 'ChIJ0d-eHXl644kR-9gAty9Z068',
  'price_level': 1,
  'rating': 4.1,
  'user_ratings_total': 3720},
 {'tag': 'North End',
  'name': 'Boston Kitchen Pizza',
  'place_id': 'ChIJ7V9fn3d644kRzotUsPPwfik',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 837},
 {'tag': 'North End',
  'name': 'Flavor Boom! Milk Street',
  'place_id': 'ChIJv4g4RB9x44kRCrHWjovnE2U',
  'price_level': 1,
  'rating': 4.8,
  'user_ratings_total': 302},
 {'tag': 'North End',
  'name': 'Jumbo Seafood',
  'place_id': 'ChIJrYKsR3h644kRhdRKR6aC7lk',
  'price_level': 2,
  'rating': 3.9,
  'user_ratings_total': 812},
 {'tag': 'North End',
  'name': 'El Palmar Restaurant',
  'place_id': 'ChIJF5JVoUlw44kRm5ovoSanUMA',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 64},
 {'tag': 'North End',
  'name': 'Bon Me - Boston Public Market',
  'place_id': 'ChIJt6NEXI9w44kRrH_axqtlJcw',
  'price_level': 1,
  'rating': 3.8,
  'user_ratings_total': 80},
 {'tag': 'North End',
  'name': 'Topacio',
  'place_id': 'ChIJuZEnQ1tw44kRIKcfHuUE-w8',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 381},
 {'tag': 'North End',
  'name': 'Row 34',
  'place_id': 'ChIJ95EjMYB644kRHrS_JLt0-Lg',
  'price_level': 3,
  'rating': 4.6,
  'user_ratings_total': 3536},
 {'tag': 'North End',
  'name': 'Mi Pueblito Restaurant',
  'place_id': 'ChIJn3q0Q1Bw44kRp-M-kvgdJNk',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 1079},
 {'tag': 'North End',
  'name': 'Kelley Square Pub',
  'place_id': 'ChIJkXA8bkVw44kRDg_40pnFqXU',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 965},
 {'tag': 'North End',
  'name': 'Umami Sushi',
  'place_id': 'ChIJe645PYNw44kRkkaFYkNpblk',
  'price_level': 1,
  'rating': 4.4,
  'user_ratings_total': 79},
 {'tag': 'North End',
  'name': 'Libertine North End',
  'place_id': 'ChIJ4VwScehx44kREVopKPp1aH0',
  'price_level': None,
  'rating': 4.2,
  'user_ratings_total': 311},
 {'tag': 'North End',
  'name': 'Cactus Mexican Grill',
  'place_id': 'ChIJ804XJF1w44kRR7oJQMlArZs',
  'price_level': 1,
  'rating': 4.3,
  'user_ratings_total': 626},
 {'tag': 'North End',
  'name': 'Tu Metapan',
  'place_id': 'ChIJx0kxu0lw44kRN5N1HA6M4lg',
  'price_level': 1,
  'rating': 4.2,
  'user_ratings_total': 204},
 {'tag': 'North End',
  'name': 'Chinese Dragon',
  'place_id': 'ChIJqVgIo1pw44kR5jziu8skJzw',
  'price_level': 1,
  'rating': 3.4,
  'user_ratings_total': 391},
 {'tag': 'North End',
  'name': 'Waverly Kitchen & Bar Charlestown',
  'place_id': 'ChIJZxEaTnFx44kRq3wYQXk-beo',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 320},
 {'tag': 'North End',
  'name': 'Pazza on Porter',
  'place_id': 'ChIJAzMVIrBx44kRn1hO8LO3fIY',
  'price_level': 2,
  'rating': 4.8,
  'user_ratings_total': 1152},
 {'tag': 'North End',
  'name': 'Restaurante Montecristo',
  'place_id': 'ChIJ1Q6IFltw44kRQEjxW7VzMic',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 516},
 {'tag': 'North End',
  'name': 'Moxies Boston Seaport Restaurant',
  'place_id': 'ChIJ28zCvCh744kRDiXNE2oj8fE',
  'price_level': None,
  'rating': 4.6,
  'user_ratings_total': 656},
 {'tag': 'North End',
  'name': 'CABANA GRILL MEXICAN RESTAURANT',
  'place_id': 'ChIJdSaiBklw44kRb1gKEHVIUKA',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 344},
 {'tag': 'North End',
  'name': 'Boston Chowda Co',
  'place_id': 'ChIJb7nX2YVw44kRWSszA1fiSY8',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 1239},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJa6jJFwx644kRCqw6ohQtC6c',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 684},
 {'tag': 'North End',
  'name': 'New York Shawarma Guys',
  'place_id': 'ChIJvxepkFJx44kR4-Zh0PP4l9I',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 276},
 {'tag': 'North End',
  'name': 'Shake Shack Downtown Crossing',
  'place_id': 'ChIJqfY6M1hx44kRhMpDOx20h58',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 1226},
 {'tag': 'North End',
  'name': 'Shōjō Boston',
  'place_id': 'ChIJRV40Onh644kRFHLE15lzefw',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 1281},
 {'tag': 'North End',
  'name': 'Falafel King - Summer Street',
  'place_id': 'ChIJzTfDV4Jw44kRreMeXT6h7M0',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 367},
 {'tag': 'North End',
  'name': 'Etnias Bar & Grill',
  'place_id': 'ChIJa-VKR_xx44kRWcgiC3k6MY8',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 77},
 {'tag': 'North End',
  'name': 'Boston Sail Loft',
  'place_id': 'ChIJKz7ENohw44kR-Aq6LJoK9Sg',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 4959},
 {'tag': 'North End',
  'name': 'LoLa 42',
  'place_id': 'ChIJ5fhUn35w44kRASBYiai3-Oo',
  'price_level': 3,
  'rating': 4.1,
  'user_ratings_total': 481},
 {'tag': 'North End',
  'name': 'La Reina Cafeteria',
  'place_id': 'ChIJE3XCa0Vw44kRZG4zEo1_v1M',
  'price_level': 1,
  'rating': 4.6,
  'user_ratings_total': 185},
 {'tag': 'North End',
  'name': "Rabia's Dolce Fumo",
  'place_id': 'ChIJ9WWwLI9w44kRsRwCZgaSYuE',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 747},
 {'tag': 'North End',
  'name': 'DIG',
  'place_id': 'ChIJuX7FWrhx44kRMPL3BFnTwN8',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 452},
 {'tag': 'North End',
  'name': 'Punto Rojo',
  'place_id': 'ChIJQWKL1Fpw44kREh_osyGnWrk',
  'price_level': 1,
  'rating': 4.5,
  'user_ratings_total': 331},
 {'tag': 'North End',
  'name': 'Rincon Limeño',
  'place_id': 'ChIJUbPD8Elw44kR8KL_ejmDDEI',
  'price_level': 2,
  'rating': 4.5,
  'user_ratings_total': 1515},
 {'tag': 'North End',
  'name': "La Famiglia Giorgio's Restaurant",
  'place_id': 'ChIJv7k_M4lw44kRuVhaTg8i9UQ',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 2860},
 {'tag': 'North End',
  'name': 'Bootleg Special',
  'place_id': 'ChIJVVUV0nN644kR1h4t-eJfIqw',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 1232},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJPV8P0oVw44kRrsrB-5wblfc',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 195},
 {'tag': 'North End',
  'name': 'sweetgreen',
  'place_id': 'ChIJNwzr4n5w44kRTQLYt6f6NTA',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 162},
 {'tag': 'North End',
  'name': 'The Daily Catch North End',
  'place_id': 'ChIJh5s-F4lw44kRVNNe4L7moqU',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 1611},
 {'tag': 'North End',
  'name': 'Cunard Tavern',
  'place_id': 'ChIJ91_I72dw44kR-qG_E1wMRcI',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 630},
 {'tag': 'North End',
  'name': 'Los Pinos Mexican Grill Restaurant',
  'place_id': 'ChIJs3A0bEVw44kRhYmT0M0Fris',
  'price_level': 2,
  'rating': 3.9,
  'user_ratings_total': 204},
 {'tag': 'North End',
  'name': "D'Parma Restaurant",
  'place_id': 'ChIJ66QUdF1w44kR6U9nceFRerY',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 550},
 {'tag': 'North End',
  'name': 'Seoul Restaurant',
  'place_id': 'ChIJ1fC9V5pw44kRM543U1ikebc',
  'price_level': 2,
  'rating': 4.1,
  'user_ratings_total': 838},
 {'tag': 'North End',
  'name': 'French Quarter',
  'place_id': 'ChIJ772OyoFx44kR4shRgUGWaBQ',
  'price_level': 2,
  'rating': 4.4,
  'user_ratings_total': 697},
 {'tag': 'North End',
  'name': 'Gaga Seafood Restaurant',
  'place_id': 'ChIJS4r5MXh644kRLFxWK1g5h_U',
  'price_level': 2,
  'rating': 4.2,
  'user_ratings_total': 420},
 {'tag': 'North End',
  'name': 'Bono Restaurant and Catering',
  'place_id': 'ChIJt20blnFx44kRKh39FoxVqvs',
  'price_level': 2,
  'rating': 4.6,
  'user_ratings_total': 143},
 {'tag': 'North End',
  'name': 'China Pearl Restaurant',
  'place_id': 'ChIJz5PKO3h644kR_zF5SEKH1Q0',
  'price_level': 2,
  'rating': 4,
  'user_ratings_total': 771},
 {'tag': 'North End',
  'name': 'Primo Pizza Restaurant',
  'place_id': 'ChIJMaYfl5tw44kRm0aMh_9Mz20',
  'price_level': 2,
  'rating': 4,
  'user_ratings_total': 102},
 {'tag': 'North End',
  'name': 'La Abundancia Bakery & Restaurant',
  'place_id': 'ChIJqTwuuVxw44kRjmO63x9ptH4',
  'price_level': 1,
  'rating': 4.3,
  'user_ratings_total': 147},
 {'tag': 'North End',
  'name': 'Union Oyster House',
  'place_id': 'ChIJMVYI84Vw44kRKNGrFHLCsVc',
  'price_level': 2,
  'rating': 4.3,
  'user_ratings_total': 9752},
 {'tag': 'North End',
  'name': 'ReelHouse',
  'place_id': 'ChIJMfUm1l1w44kRxwjqOp81giY',
  'price_level': 3,
  'rating': 4.2,
  'user_ratings_total': 1258},
 {'tag': 'North End',
  'name': 'GRECO',
  'place_id': 'ChIJnz5X7w5644kR5mYdtXjIX6o',
  'price_level': 1,
  'rating': 4.6,
  'user_ratings_total': 1491},
 {'tag': 'North End',

In [53]:
import pandas as pd
rest_df = pd.DataFrame(restaurants)
# rest_df = rest_df.drop_duplicates(subset=['place_id'])

In [55]:
rest_df.to_csv('rest_by place.csv')

In [58]:
def rating_bins(row):
    if row['user_ratings_total'] == 0:
        return "0 ratings"
    elif row['user_ratings_total'] <= 100:
        return "1-100 ratings"
    elif row['user_ratings_total'] <= 500:
        return "101-500 ratings"
    elif row['user_ratings_total'] <= 1000:
        return "501-1000 ratings"
    elif row['user_ratings_total'] <= 2000:
        return "1001-2000 ratings"
    elif row['user_ratings_total'] <= 3000:
        return "2001-3000 ratings"
    else:
        return "3000+ ratings"
    
rest_df['rating_bin'] = rest_df.apply(lambda row: rating_bins(row), axis=1 )
rest_df['rating_bin'] = pd.Categorical(rest_df['rating_bin'], 
                      categories=["0 ratings","1-100 ratings","101-500 ratings","501-1000 ratings","1001-2000 ratings","2001-3000 ratings", "3000+ ratings"],
                      ordered=True)

In [61]:
rest_df[rest_df.duplicated(['tag','place_id'],keep=False)]

Empty DataFrame
Columns: [tag, name, place_id, price_level, rating, user_ratings_total, rating_bin]
Index: []

In [66]:
rest_df['rating_bin']=rest_df['rating_bin'].astype(str)

In [77]:
rest_df_agg=pd.pivot_table(rest_df, values ='name', index =['tag'], 
                         columns =['rating_bin'], aggfunc ='count',fill_value=0) 

rest_df_agg['0-500']=rest_df_agg['0 ratings']+rest_df_agg['1-100 ratings']+rest_df_agg['101-500 ratings']
rest_df_agg['1000+ rating']=rest_df_agg['1001-2000 ratings']+rest_df_agg['2001-3000 ratings']+rest_df_agg['3000+ ratings']
rest_df_agg.drop(['0 ratings','1-100 ratings','101-500 ratings','1001-2000 ratings','2001-3000 ratings','3000+ ratings'],axis=1,inplace=True)

In [84]:
rest_df_agg.reset_index(inplace=True)

In [90]:
new_df=pd.DataFrame()

In [94]:
new_df['source']=rest_df_agg.apply(lambda x: x['tag'][0],axis=1)
new_df['latitude']=rest_df_agg.apply(lambda x: x['tag'][1],axis=1)
new_df['longitude']=rest_df_agg.apply(lambda x: x['tag'][2],axis=1)
new_df['501-1000 ratings']=rest_df_agg.apply(lambda x: x['501-1000 ratings'],axis=1)
new_df['0-500 ratings']=rest_df_agg.apply(lambda x: x['0-500'],axis=1)
new_df['1000+ ratings']=rest_df_agg.apply(lambda x: x['1000+ rating'],axis=1)

In [98]:
uber_df=pd.merge(uber_df,new_df,on=['source','latitude','longitude'],how='left')

In [100]:
restaurants = []
def restaurant_response(response_items, tag):
    restaurant_responses = []
    for item in response_items:
        item_dict = {}
        item_dict['tag'], item_dict['name'], item_dict['place_id'], item_dict['price_level'], item_dict['rating'], item_dict['user_ratings_total'] = tag, item.get('name'), item.get('place_id'), item.get('price_level'), item.get('rating'), item.get('user_ratings_total')
        restaurant_responses.append(item_dict)
    return restaurant_responses


for i,barrio in enumerate(regions):
    query_barrio = barrio[0] + " Boston"
    lat = barrio[1]
    lng = barrio[2]
    flag = False
    counter = 0
    while flag == False:
        if counter == 0:
            results = gmaps.places(type="hospital", location=[lat, lng], radius=2000)
            response_items = results['results']
            restaurants.extend(restaurant_response(response_items, barrio))
            counter += 1
        else:
            if results.get('next_page_token') is None:
                flag = True
            else:
                next_page = results.get('next_page_token')
                time.sleep(2)
                results = gmaps.places(type="hospital", location=[lat, lng], radius=2000, page_token=next_page)
                response_items = results['results']
                restaurants.extend(restaurant_response(response_items, barrio))
                counter += 1

In [102]:
hospitals=restaurants

In [108]:
hospital_df = pd.DataFrame(hospitals)

In [105]:
hospital_df.to_csv('hospital.csv')

In [127]:
hospital_df.drop_duplicates(['tag','name'],keep='first',inplace=True)

In [299]:
hospital_df=hospital_df[hospital_df['user_ratings_total']>1000]
uber_df.drop('hosp_cnt',axis=1,inplace=True)

In [300]:
hospital_df_agg=hospital_df.groupby(['tag']).agg({'name':'nunique'})
hospital_df_agg.reset_index(inplace=True)

new_df=pd.DataFrame()
new_df['source']=hospital_df_agg.apply(lambda x: x['tag'][0],axis=1)
new_df['latitude']=hospital_df_agg.apply(lambda x: x['tag'][1],axis=1)
new_df['longitude']=hospital_df_agg.apply(lambda x: x['tag'][2],axis=1)
new_df['hosp_cnt']=hospital_df_agg.apply(lambda x: x['name'],axis=1)

In [301]:
uber_df=pd.merge(uber_df,new_df,on=['source','latitude','longitude'],how='left')

In [134]:
stadiums = []
def stadium_response(response_items, tag):
    stadium_responses = []
    for item in response_items:
        item_dict = {}
        item_dict['tag'], item_dict['name'], item_dict['place_id'], item_dict['price_level'], item_dict['rating'], item_dict['user_ratings_total'] = tag, item.get('name'), item.get('place_id'), item.get('price_level'), item.get('rating'), item.get('user_ratings_total')
        stadium_responses.append(item_dict)
    return stadium_responses


for i,barrio in enumerate(regions):
    query_barrio = barrio[0] + " Boston"
    lat = barrio[1]
    lng = barrio[2]
    flag = False
    counter = 0
    while flag == False:
        if counter == 0:
            results = gmaps.places(type="stadium", location=[lat, lng], radius=2000)
            response_items = results['results']
            stadiums.extend(stadium_response(response_items, barrio))
            counter += 1
        else:
            if results.get('next_page_token') is None:
                flag = True
            else:
                next_page = results.get('next_page_token')
                time.sleep(2)
                results = gmaps.places(type="stadium", location=[lat, lng], radius=2000, page_token=next_page)
                response_items = results['results']
                stadiums.extend(stadium_response(response_items, barrio))
                counter += 1

In [286]:
stadium_df=stadium_df[stadium_df['user_ratings_total']>500]
uber_df.drop('stadium_cnt',axis=1,inplace=True)

In [287]:
# stadium_df=pd.DataFrame(stadiums)
stadium_df.drop_duplicates(['tag','name'],keep='first', inplace=True)

stadium_df_agg=stadium_df.groupby(['tag']).agg({'name':'nunique'})
stadium_df_agg.reset_index(inplace=True)

new_df=pd.DataFrame()
new_df['source']=stadium_df_agg.apply(lambda x: x['tag'][0],axis=1)
new_df['latitude']=stadium_df_agg.apply(lambda x: x['tag'][1],axis=1)
new_df['longitude']=stadium_df_agg.apply(lambda x: x['tag'][2],axis=1)
new_df['stadium_cnt']=stadium_df_agg.apply(lambda x: x['name'],axis=1)

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\3056388629.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stadium_df.drop_duplicates(['tag','name'],keep='first', inplace=True)

In [288]:
uber_df=pd.merge(uber_df,new_df,on=['source','latitude','longitude'],how='left')

In [155]:
uber_df['name'].unique()

array(['UberXL', 'Black', 'UberX', 'WAV', 'Black SUV', 'UberPool', 'Taxi'],
      dtype=object)

In [ ]:
# 'UberPool', 'Taxi','UberX','UberXL','Black', 'Black SUV', 'WAV'

In [175]:
uber_df['booking_hour_int']=uber_df['booking_hour'].apply(lambda x: int(str(x).split(":")[0]))

In [190]:
### only Taxi prices are null hence substituting them with grouped mean of UberX
uber_df.loc[(uber_df['name']=='Taxi'),'name_new']='UberX'
uber_df['price']=uber_df.groupby(['name_new','source','destination','booking_hour_int'])['price'].transform(lambda x: x.fillna(x.mean()))

In [223]:
x=pd.DataFrame(uber_df.isnull().sum(),columns=['Cnt']).reset_index()

In [221]:
uber_df.fillna(0,inplace=True)

In [226]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['UberPool', 'Taxi','UberX','UberXL','Black', 'Black SUV', 'WAV']])
uber_df['name_rank']=encoder.fit_transform(uber_df[['name']])

In [255]:
## Cyclical features are booking_day, booking_month, booking_hour_int, booking_weekday

In [251]:
from sklearn.preprocessing import FunctionTransformer


def sin_transformer(period):
    return FunctionTransformer(lambda x: np.sin(x / period * 2 * np.pi))


def cos_transformer(period):
    return FunctionTransformer(lambda x: np.cos(x / period * 2 * np.pi))


uber_df["booking_day_sin"] = uber_df.apply(lambda x: np.sin(x['booking_day'] / 31 * 2 * np.pi),axis=1)
uber_df["booking_day_cos"] = uber_df.apply(lambda x: np.cos(x['booking_day'] / 31 * 2 * np.pi),axis=1)

uber_df["booking_month_sin"] = uber_df.apply(lambda x: np.sin(x['booking_month'] / 12 * 2 * np.pi),axis=1)
uber_df["booking_month_cos"] = uber_df.apply(lambda x: np.cos(x['booking_day'] / 12 * 2 * np.pi),axis=1)

uber_df["booking_hour_int_sin"] = uber_df.apply(lambda x: np.sin(x['booking_hour_int'] / 24 * 2 * np.pi),axis=1)
uber_df["booking_hour_int_cos"] = uber_df.apply(lambda x: np.cos(x['booking_hour_int'] / 24 * 2 * np.pi),axis=1)

uber_df["booking_weekday_sin"] = uber_df.apply(lambda x: np.sin(x['booking_weekday'] / 7 * 2 * np.pi),axis=1)
uber_df["booking_weekday_cos"] = uber_df.apply(lambda x: np.cos(x['booking_weekday'] / 7 * 2 * np.pi),axis=1)

In [403]:
uber_df.columns.to_list()

['id',
 'timezone',
 'source',
 'destination',
 'cab_type',
 'product_id',
 'name',
 'price',
 'distance',
 'surge_multiplier',
 'latitude',
 'longitude',
 'temperature',
 'apparentTemperature',
 'short_summary',
 'long_summary',
 'precipIntensity',
 'precipProbability',
 'humidity',
 'windSpeed',
 'windGust',
 'visibility',
 'icon',
 'dewPoint',
 'pressure',
 'windBearing',
 'cloudCover',
 'uvIndex',
 'visibility.1',
 'ozone',
 'moonPhase',
 'precipIntensityMax',
 'temperatureMin',
 'temperatureMax',
 'booking_time',
 'booking_date',
 'booking_day',
 'booking_month',
 'booking_year',
 'booking_hour',
 'booking_weekday',
 'booking_day_weekend',
 'booking_minute',
 'windGustTime_hour',
 'temperatureHighTime_hour',
 'temperatureLowTime_hour',
 'sunriseTime_hour',
 'sunsetTime_hour',
 'uvIndexTime_hour',
 'temperatureMinTime_hour',
 'temperatureMaxTime_hour',
 'temp_var',
 'dist_cat',
 'temperature_2_day_mov_avg',
 'precipIntensity_2_day_mov_avg',
 'humidity_2_day_mov_avg',
 'ozone_2_day_mov_avg',
 'temperature_7_day_mov_avg',
 'precipIntensity_7_day_mov_avg',
 'humidity_7_day_mov_avg',
 'ozone_7_day_mov_avg',
 'temperature_14_day_mov_avg',
 'precipIntensity_14_day_mov_avg',
 'humidity_14_day_mov_avg',
 'ozone_14_day_mov_avg',
 'temperature_30_day_mov_avg',
 'precipIntensity_30_day_mov_avg',
 'humidity_30_day_mov_avg',
 'ozone_30_day_mov_avg',
 'precipIntensity_diff_2',
 'precipIntensity_diff_7',
 'precipIntensity_diff_14',
 'precipIntensity_diff_30',
 'temperature_diff_2',
 'temperature_diff_7',
 'temperature_diff_14',
 'temperature_diff_30',
 'humidity_diff_2',
 'humidity_diff_7',
 'humidity_diff_14',
 'humidity_diff_30',
 'ozone_diff_2',
 'ozone_diff_7',
 'ozone_diff_14',
 'ozone_diff_30',
 'bktime_tmpmaxtime_diff',
 'bktime_sunrisetime_diff',
 'bktime_sunsettime_diff',
 '501-1000 ratings',
 '0-500 ratings',
 '1000+ ratings',
 'booking_hour_int',
 'name_new',
 'name_rank',
 'booking_day_sin',
 'booking_day_cos',
 'booking_month_sin',
 'booking_month_cos',
 'booking_hour_int_sin',
 'booking_hour_int_cos',
 'booking_weekday_sin',
 'booking_weekday_cos',
 'stadium_cnt',
 'hosp_cnt']

In [404]:
model_df=uber_df[['price','name_rank','surge_multiplier','temperature', 'precipIntensity', 'precipProbability', 'humidity',
       'windSpeed', 'windGust', 'visibility',  'dewPoint', 'pressure',
       'windBearing', 'cloudCover', 'uvIndex', 'visibility.1', 'ozone',
       'moonPhase', 'booking_day_sin', 'booking_day_cos',
       'booking_month_sin', 'booking_month_cos', 'booking_hour_int_sin',
       'booking_hour_int_cos', 'booking_weekday_sin', 'booking_weekday_cos',
       'booking_day_weekend', 'temp_var',
       'dist_cat', 'temperature_2_day_mov_avg',
       'precipIntensity_2_day_mov_avg', 'humidity_2_day_mov_avg',
       'ozone_2_day_mov_avg', 'temperature_7_day_mov_avg',
       'precipIntensity_7_day_mov_avg', 'humidity_7_day_mov_avg',
       'ozone_7_day_mov_avg', 'temperature_14_day_mov_avg',
       'precipIntensity_14_day_mov_avg', 'humidity_14_day_mov_avg',
       'ozone_14_day_mov_avg', 'temperature_30_day_mov_avg',
       'precipIntensity_30_day_mov_avg', 'humidity_30_day_mov_avg',
       'ozone_30_day_mov_avg', 'precipIntensity_diff_2',
       'precipIntensity_diff_7', 'precipIntensity_diff_14',
       'precipIntensity_diff_30', 'temperature_diff_2', 'temperature_diff_7',
       'temperature_diff_14', 'temperature_diff_30', 'humidity_diff_2',
       'humidity_diff_7', 'humidity_diff_14', 'humidity_diff_30',
       'ozone_diff_2', 'ozone_diff_7', 'ozone_diff_14', 'ozone_diff_30',
       'bktime_tmpmaxtime_diff', 'bktime_sunrisetime_diff',
       'bktime_sunsettime_diff', '501-1000 ratings', '0-500 ratings',
       '1000+ ratings', 'hosp_cnt', 'stadium_cnt','temperature']]

In [405]:
x=pd.get_dummies(model_df['dist_cat'],drop_first=True)
model_df=pd.merge(model_df,x,left_index=True,right_index=True)

In [406]:
model_df.drop('dist_cat',axis=1,inplace=True)

In [419]:
model_df['stadium_cnt']=model_df['stadium_cnt'].fillna(0)

In [421]:
model_df['(4-6]']=model_df['(4-6]'].astype(int)
model_df['(6-8]']=model_df['(6-8]'].astype(int)
model_df['[0,2]']=model_df['[0,2]'].astype(int)

In [432]:
from sklearn.preprocessing import StandardScaler,RobustScaler

scaler=StandardScaler()
model_df_new=pd.DataFrame(scaler.fit_transform(model_df.drop(['booking_day_sin', 'booking_day_cos',
       'booking_month_sin', 'booking_month_cos', 'booking_hour_int_sin',
       'booking_hour_int_cos', 'booking_weekday_sin', 'booking_weekday_cos','(4-6]', '(6-8]', '[0,2]'],axis=1)),columns=model_df.drop(['booking_day_sin', 'booking_day_cos',
       'booking_month_sin', 'booking_month_cos', 'booking_hour_int_sin',
       'booking_hour_int_cos', 'booking_weekday_sin', 'booking_weekday_cos','(4-6]', '(6-8]', '[0,2]'],axis=1).columns)

model_df_new=pd.merge(model_df_new,model_df[['booking_day_sin', 'booking_day_cos',
       'booking_month_sin', 'booking_month_cos', 'booking_hour_int_sin',
       'booking_hour_int_cos', 'booking_weekday_sin', 'booking_weekday_cos','(4-6]', '(6-8]', '[0,2]']],left_index=True,right_index=True)

In [592]:
final=model_df_new[[
   'booking_weekday_cos', 'name_rank', '[0,2]', 'surge_multiplier', '(4-6]', '(6-8]',
                    
'price']]

In [447]:
 from statsmodels.stats.outliers_influence import variance_inflation_factor

# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = model_df_new.columns

# calculating VIF for each feature
vif_data["VIF"] = [round(variance_inflation_factor(model_df_new[model_df_new.columns].values, i),0)
                          for i in range(len(model_df_new.columns))]

print(vif_data)

C:\Users\Amrita\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1738: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

                feature        VIF
0                 price        1.0
1             name_rank        1.0
2      surge_multiplier        NaN
3           temperature  4038043.0
4       precipIntensity  4038043.0
..                  ...        ...
67  booking_weekday_sin        3.0
68  booking_weekday_cos        2.0
69                (4-6]       16.0
70                (6-8]        3.0
71                [0,2]        1.0

[72 rows x 2 columns]

In [445]:
# vif_data.to_csv("vif.csv")

In [593]:

import statsmodels.api as sm
# adding the constant term
final = sm.add_constant(final)

# performing the regression
# and fitting the model
result = sm.OLS(final['price'], final.drop('price',axis=1)).fit()

# printing the summary table
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.321
Model:                            OLS   Adj. R-squared:                  0.321
Method:                 Least Squares   F-statistic:                 3.651e+04
Date:                Tue, 04 Mar 2025   Prob (F-statistic):               0.00
Time:                        08:11:37   Log-Likelihood:            -4.7251e+05
No. Observations:              385663   AIC:                         9.450e+05
Df Residuals:                  385657   BIC:                         9.451e+05
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                   0.1602      0.002     81.042      0.000       0.156       0.164
booking_weekday_cos     0.0019      0.002      1.030      0.303      -0.002       0.005
name_rank               0.4759      0.001    358.697      0.000       0.473       0.478
[0,2]                  -0.4341      0.003   -157.592      0.000      -0.439      -0.429
surge_multiplier     -5.11e-17   1.43e-19   -357.793      0.000   -5.14e-17   -5.08e-17
(4-6]                   0.5936      0.006    104.469      0.000       0.583       0.605
(6-8]                   0.9674      0.014     70.905      0.000       0.941       0.994
==============================================================================
Omnibus:                     8179.721   Durbin-Watson:                   2.156
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9776.587
Skew:                           0.303   Prob(JB):                         0.00
Kurtosis:                       3.492   Cond. No.                     1.26e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.12e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [352]:
X=model_df_new.drop('price',axis=1)
y=model_df_new['price']

In [589]:
initial=[
   'pressure',
'bktime_sunrisetime_diff',
'booking_month_cos',
'booking_day_weekend',
'booking_hour_int_sin',
'windBearing',
'(4-6]',
'windGust',
'visibility',
'stadium_cnt',
'booking_month_sin',
'humidity',
'booking_hour_int_cos',
'temp_var',
'temperature',
'cloudCover',
'temperature_2_day_mov_avg',
'booking_weekday_sin',
'(6-8]',
'uvIndex',
'visibility.1',
'booking_weekday_cos',
'name_rank',
'[0,2]',
'surge_multiplier']

In [590]:
#Stepwise variable elimination method for linear regression with in and out p-value thresholds implementation
def stepwise_selection(X, y,
                       initial_list = initial,
                       threshold_in=0.001, 
                       threshold_out = 0.01, 
                       verbose=True):
    """ Perform a forward-backward feature selection 
    based on p-value from statsmodels.api.OLS
    Arguments:
        X - pandas.DataFrame with candidate features
        y - list-like with the target
        initial_list - list of features to start with (column names of X)
        threshold_in - include a feature if its p-value < threshold_in
        threshold_out - exclude a feature if its p-value > threshold_out
        verbose - whether to print the sequence of inclusions and exclusions
    Returns: list of selected features 
    Always set threshold_in < threshold_out to avoid infinite looping.
    See https://en.wikipedia.org/wiki/Stepwise_regression for the details
    """
    included = initial_list
    while True:
        changed=False
        # forward step
        excluded = list(set(X.columns)-set(included))
        new_pval = pd.Series(index=excluded)
        for new_column in excluded:
            model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included+[new_column]]))).fit()
            new_pval[new_column] = model.pvalues[new_column]
        best_pval = new_pval.min()
        if best_pval < threshold_in:
            best_feature = new_pval[new_pval==new_pval.min()].index[0]
            included.append(best_feature)
            changed=True
            if verbose:
                print('Add  {:30} with p-value {:.6}'.format(best_feature, best_pval))

        # backward step
        model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included]))).fit()
        # use all coefs except intercept
        pvalues = model.pvalues.iloc[1:]
        worst_pval = pvalues.max() # null if pvalues is empty
        if worst_pval > threshold_out:
            changed=True
            worst_feature = included[pvalues.argmax()]
            included.remove(worst_feature)
            if verbose:
                print('Drop {:30} with p-value {:.6}'.format(worst_feature, worst_pval))
        if not changed:
            break
    return included

In [591]:
#Computing the best model automatically
result = stepwise_selection(X, y)
print('resulting features:')
print(result)

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop booking_hour_int_cos           with p-value 0.863736

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop windGust                       with p-value 0.892288

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop temperature                    with p-value 0.839112

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop booking_hour_int_sin           with p-value 0.985495

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop booking_day_weekend            with p-value 0.961662

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop (4-6]                          with p-value 0.849414

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Add  (4-6]                          with p-value 0.0
Drop windBearing                    with p-value 0.849414

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop humidity                       with p-value 0.938078

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop booking_month_sin              with p-value 0.92043

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop uvIndex                        with p-value 0.96457

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop booking_month_cos              with p-value 0.925249

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop stadium_cnt                    with p-value 0.904105

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop visibility                     with p-value 0.966691

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop bktime_sunrisetime_diff        with p-value 0.966691

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop pressure                       with p-value 0.975723

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop (6-8]                          with p-value 0.920436

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Add  (6-8]                          with p-value 0.0
Drop booking_weekday_sin            with p-value 0.920436

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop temperature_2_day_mov_avg      with p-value 0.881219

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop cloudCover                     with p-value 0.856766

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop temp_var                       with p-value 0.776232

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

Drop visibility.1                   with p-value 0.463457

C:\Users\Amrita\AppData\Local\Temp\ipykernel_11896\927674810.py:25: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

resulting features:
['booking_weekday_cos', 'name_rank', '[0,2]', 'surge_multiplier', '(4-6]', '(6-8]']

In [ ]:
#Another way to handle mutli collinearity in the data using Gradient Boosting Regressor
def greedy_elim(df):

    # do feature selection using boruta
    X = df[[x for x in df.columns if x!='GMV']]
    y = df['GMV']
    #model = RandomForestRegressor(n_estimators=50)
    model = GradientBoostingRegressor(n_estimators=50, learning_rate=0.05)
    # 150 features seems to be the best at the moment. Why this is is unclear.
    feat_selector = RFE(estimator=model, step=1, n_features_to_select=6)

    # find all relevant features
    feat_selector.fit_transform(X.as_matrix(), y.as_matrix())

    # check selected features
    features_bool = np.array(feat_selector.support_)
    features = np.array(X.columns)
    result = features[features_bool]
    #print(result)

    # check ranking of features
    features_rank = feat_selector.ranking_
    #print(features_rank)
    rank = features_rank[features_bool]
    #print(rank)

    return result 
from sklearn.ensemble import GradientBoostingRegressor
greedy_elim(ConsumerElectronics_gaming_full)